rubymonsters/rgbapp

- app/models/application.rb
- app/views/applications/new.html.erb
I created a menu for the level (number field) and a drop-down menu to select the OS. I added a blank option in case someone does not have computer.
> Add improvements to form

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.css
- app/controllers/application_controller.rb
- app/controllers/applications_controller.rb
- app/models/application.rb
- app/models/user.rb
- app/views/applications/index.html.erb
- app/views/layouts/application.html.erb
- config/initializers/clearance.rb
- db/migrate/20170619174833_create_users.rb
- db/migrate/20170626192116_add_admin_to_user.rb
- db/schema.rb
> Add sign-in and applicants list

- app/assets/stylesheets/application.css
- app/controllers/applications_controller.rb
- app/helpers/applications_helper.rb
- app/views/applications/index.html.erb
We need to check whether sql injection is possible.
> Make table sortable

- app/controllers/applications_controller.rb
- app/models/application.rb
- app/views/applications/index.html.erb
Created a link that allows export of applicants in table to a csv format download.
> Export csv

- .travis.yml
- README.md
So that it runs the tests for us after each pull request or merge 😸
> Configure Travis

- .gitignore
- .travis.yml
- Gemfile
- Gemfile.lock
- app/controllers/applications_controller.rb
- app/views/applications/index.html.erb
- test/application_system_test_case.rb
- test/system/select_applicants_test.rb
It also adds a system test to reproduce the bug.
> Fixes bug when unselecting all applicants

- app/controllers/applications_controller.rb
- app/mailers/user_mailer.rb
- app/views/applications/create.html.erb
- app/views/user_mailer/application_mail.text.erb
- test/mailers/previews/user_mailer_preview.rb
- test/mailers/user_mailer_test.rb
We created the mailer but still need the email message text. @Powerglove do you have any suggestions?
> Add application email (fixes #11)

- app/views/layouts/application.html.erb
I changed the title to the format used on the Rails Girls Berlin website.
> Change tab title fixes #41

- app/models/application.rb
- config/locales/en.yml
Not sure whether this is the best solution but it works.
> Change display of booleans in csv export fixes #32

- app/assets/javascripts/events.coffee
- app/assets/stylesheets/events.scss
- app/controllers/events_controller.rb
- app/helpers/events_helper.rb
- app/views/events/index.html.erb
- config/routes.rb
- db/schema.rb
- test/controllers/events_controller_test.rb
This PR solves issue #43 (Show a list of available events)
> Show a list of available events 

- app/controllers/applications_controller.rb
- app/controllers/events_controller.rb
- app/mailers/user_mailer.rb
- app/views/applications/confirm.html.erb
- app/views/applications/confirmed_too_late.html.erb
- app/views/applications/index.html.erb
- app/views/user_mailer/selection_mail.text.erb
- config/routes.rb
- db/migrate/20180115183749_add_attendance_confirmed_to_applications.rb
- db/migrate/20180115190413_add_random_i_dto_applications.rb
- db/migrate/20180129192321_add_selected_on_to_applications.rb
- db/schema.rb
Pending: Still need to write the e-mail text.
> Send selection email fixes #49

- app/models/event.rb
- app/views/user_mailer/selection_mail.text.erb
- db/migrate/20180122202409_add_event_time.rb
- db/schema.rb
- test/controllers/applications_controller_test.rb
- test/factories.rb
- test/system/select_applicants_test.rb
> Add event time in DB

- app/controllers/admin/events_controller.rb
- app/views/admin/events/edit.html.erb
- test/system/delete_event_test.rb
- test/system/edit_event_test.rb
> Create possibility to delete events

- app/assets/javascripts/admin/users.coffee
- app/assets/stylesheets/admin/users.scss
- app/controllers/admin/users_controller.rb
- app/helpers/admin/users_helper.rb
- app/views/admin/users/index.html.erb
- config/routes.rb
- test/controllers/admin/users_controller_test.rb
- test/system/admin_users_test.rb
> Add table of users and button to make user an admin fixes #77

- app/controllers/admin/applications_controller.rb
- app/controllers/admin/events_controller.rb
- app/controllers/admin/users_controller.rb
- app/helpers/application_helper.rb
- app/views/admin/events/edit.html.erb
- app/views/admin/events/index.html.erb
- app/views/layouts/admin.html.erb
- config/routes.rb
- test/system/add_event_test.rb
- test/system/delete_event_test.rb
- test/system/edit_event_test.rb
To do: add link to applicants list in events list
> Add admin layout for navigation fixes #76

- app/controllers/admin/events_controller.rb
- app/models/event.rb
- app/views/admin/events/edit.html.erb
- test/system/add_event_test.rb
> Copy templates fixes #113

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css
- app/helpers/admin/templates_helper.rb
- app/mailers/user_mailer.rb
- app/views/admin/templates/edit.html.erb
- config/environments/development.rb
- test/system/add_event_test.rb
In progress. We still need to test how it works and rewrite the test that we commented.
> Add Trix for email templates fixes #123

- app/models/application.rb
- config/locales/en.yml
I'm displaying the 3 states (rejected, waiting list, selected) in one column in the csv. Is that OK for you @ferbsx? Don't know how to keep the three columns in the csv.
> Add status and confirmed column to csv export fixes #188

- app/assets/stylesheets/application.css
- app/controllers/admin/applications_controller.rb
- app/controllers/admin/coach_applications_controller.rb
- app/helpers/coach_applications_helper.rb
- app/models/coach_application.rb
- app/views/admin/applications/index.html.erb
- app/views/admin/coach_applications/index.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20191111184530_add_column_coach_state.rb
- db/schema.rb
- test/system/select_coaches_test.rb
Added a coach status column with different states
See issue #214 (approval for coaches)
> Coach approval

- .rubocop_todo.yml
- app/controllers/admin/coach_applications_controller.rb
- app/views/admin/coach_applications/index.html.erb
- db/migrate/20191202183522_add_lightningtalk_approval.rb
- db/schema.rb
- test/system/select_coaches_test.rb
- test/test_helper.rb
> Add lightning talk approval column

- app/controllers/coach_applications_controller.rb
- app/views/coach_applications/new.html.erb
- db/migrate/20200210194758_add_first_time_coaching_to_coach_applications.rb
- db/schema.rb
Add "first time coaching" feature to coach application form
> first time coaching

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Add standard templates for bug reports and feature requests. Should we use these?
> Update issue templates closes #260

- README.md
Should I add more information?
> Add section on contributing #closes 259
